language: node_js

node_js:
  - "--lts"

python:
  - 2.7.13

cache:
  directories:
    - node_modules

install:
  - npm install
  
after_success:
  - grunt update-networks

notifications:
  irc: "irc.freenode.net#sickrage-builds"
  email:
    on_success: change
    on_failure: change
